spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/razorpay_demo
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

razorpay.key.id=rzp_test_T5nypDHplHxJ9C



razorpay.key.secret=IRz3wLt3Mk3rF4q2i38TUwZk